name: setup-svu
description: "Install & use SVU semver tool"
author: "@obfu5c8"
runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  type:
    required: false
    description: "Bump type. Can be 'none', 'major', 'minor', 'patch', 'auto'"
    default: "auto"

  force-increment:
    required: false
    description: Force at least a patch increment, even if no commits demand it
    default: "false"

  tag-mode:
    required: false
    description: |
      Change 'last tag' lookup behaviour. Accepted values are 'current-branch' and 'all-branches'
    default: "current-branch"

  no-metadata:
    required: false
    description: Discards pre-release and build metadata
    default: "false"

  no-pre-release:
    required: false
    description: Discards pre-release metadata
    default: "false"

  no-build:
    required: false
    description: Discards build metadata
    default: "false"

  strip-prefix:
    required: false
    description: Removes any prefix from the version output. For example, `v1.2.3`` would be output as `1.2.3`
    default: "false"

  prefix:
    required: false
    description: The prefix of the tag. Default is `v`
    default: "v"

  suffix:
    required: false
    description: Can be used to set a custom suffix for the tag, e.g. build metadata or prelease
    default: ""

  svu-version:
    required: false
    description: Override the default SVU release to install
    default: "1.9.0"

outputs:
  version:
    description: The resulting new version

  bin_path:
    description: The path to the svu binary
